POST http://localhost:3000/passengers HTTP/1.1
Content-Type: application/json

{"name": "Client" , "location": "kuzguncuk"}

###

GET http://localhost:3000/passengers/678292faa8c8b7f9df53764b HTTP/1.1

###

DELETE  http://localhost:3000/passengers/67825b456339085e6680c396 HTTP/1.1

###

PATCH  http://localhost:3000/passengers/6782703302c17f1c67d76cd7 HTTP/1.1
Content-Type: application/json

{"name": "Enes" , "location": "Yesilyurt"}

###

POST http://localhost:3000/drivers HTTP/1.1
Content-Type: application/json

{"name": "Mücahid" , "location": "kuzguncuk"}

###

DELETE  http://localhost:3000/drivers/6782708602c17f1c67d76cdb HTTP/1.1

###

POST http://localhost:3000/passengers/678292faa8c8b7f9df53764b/bookings HTTP/1.1
Content-Type: application/json

{
  "driverId": "6782930ca8c8b7f9df53764f",
  "origin": "Bebek",
  "destination": "Maltepe"
}

###

PATCH  http://localhost:3000/drivers/6782930ca8c8b7f9df53764f HTTP/1.1
Content-Type: application/json

{"name": "Eyüp"}
