POST http://localhost:3000/passengers HTTP/1.1
Content-Type: application/json

{"name": "Client" , "location": "YesilTeper"}

###

GET http://localhost:3000/passengers/67825b456339085e6680c396 HTTP/1.1

###

DELETE  http://localhost:3000/passengers/67825b456339085e6680c396 HTTP/1.1

###

PATCH  http://localhost:3000/passengers/67825b6d6339085e6680c39c HTTP/1.1
Content-Type: application/json

{"name": "New Client 55" , "location": "Yesilyurt"}

